import type { NewEnergyReserve } from "./schema.js";

/**
 * Major energy reserves worldwide with accurate geographic coordinates.
 *
 * Sources for coordinates and estimates:
 * - EIA (U.S. Energy Information Administration)
 * - OPEC Annual Statistical Bulletin
 * - BP Statistical Review of World Energy
 * - USGS assessments
 *
 * Types: "oil" | "natural_gas" | "coal" | "oil_sands" | "shale"
 * Units: Bbbl (billion barrels), Tcf (trillion cubic feet), Bt (billion tonnes)
 */
export const ENERGY_RESERVES: Omit<NewEnergyReserve, "id">[] = [
  // ──────────────── Conventional Oil ────────────────
  {
    name: "Ghawar Field",
    type: "oil",
    subtype: "conventional",
    lat: 25.383,
    lng: 49.567,
    estimatedReserves: 48,
    unit: "Bbbl",
    country: "Saudi Arabia",
    iso3: "SAU",
    year: 2024,
  },
  {
    name: "Burgan Field",
    type: "oil",
    subtype: "conventional",
    lat: 29.067,
    lng: 47.917,
    estimatedReserves: 40,
    unit: "Bbbl",
    country: "Kuwait",
    iso3: "KWT",
    year: 2024,
  },
  {
    name: "Safaniya Field",
    type: "oil",
    subtype: "conventional",
    lat: 28.833,
    lng: 49.417,
    estimatedReserves: 37,
    unit: "Bbbl",
    country: "Saudi Arabia",
    iso3: "SAU",
    year: 2024,
  },
  {
    name: "Rumaila Field",
    type: "oil",
    subtype: "conventional",
    lat: 30.4,
    lng: 47.333,
    estimatedReserves: 17.8,
    unit: "Bbbl",
    country: "Iraq",
    iso3: "IRQ",
    year: 2024,
  },
  {
    name: "Bolivar Coastal Field",
    type: "oil",
    subtype: "conventional",
    lat: 10.317,
    lng: -71.383,
    estimatedReserves: 30,
    unit: "Bbbl",
    country: "Venezuela",
    iso3: "VEN",
    year: 2024,
  },
  {
    name: "Samotlor Field",
    type: "oil",
    subtype: "conventional",
    lat: 61.183,
    lng: 76.7,
    estimatedReserves: 14,
    unit: "Bbbl",
    country: "Russia",
    iso3: "RUS",
    year: 2024,
  },
  {
    name: "Prudhoe Bay",
    type: "oil",
    subtype: "conventional",
    lat: 70.267,
    lng: -148.7,
    estimatedReserves: 12,
    unit: "Bbbl",
    country: "United States",
    iso3: "USA",
    year: 2024,
  },
  {
    name: "Daqing Field",
    type: "oil",
    subtype: "conventional",
    lat: 46.6,
    lng: 125.0,
    estimatedReserves: 6.3,
    unit: "Bbbl",
    country: "China",
    iso3: "CHN",
    year: 2024,
  },
  {
    name: "Cantarell Complex",
    type: "oil",
    subtype: "conventional",
    lat: 19.517,
    lng: -92.0,
    estimatedReserves: 4.5,
    unit: "Bbbl",
    country: "Mexico",
    iso3: "MEX",
    year: 2024,
  },
  {
    name: "Kashagan Field",
    type: "oil",
    subtype: "conventional",
    lat: 46.2,
    lng: 51.517,
    estimatedReserves: 13,
    unit: "Bbbl",
    country: "Kazakhstan",
    iso3: "KAZ",
    year: 2024,
  },
  {
    name: "Tengiz Field",
    type: "oil",
    subtype: "conventional",
    lat: 46.15,
    lng: 53.333,
    estimatedReserves: 25.5,
    unit: "Bbbl",
    country: "Kazakhstan",
    iso3: "KAZ",
    year: 2024,
  },
  {
    name: "Upper Zakum Field",
    type: "oil",
    subtype: "conventional",
    lat: 24.85,
    lng: 53.2,
    estimatedReserves: 21,
    unit: "Bbbl",
    country: "UAE",
    iso3: "ARE",
    year: 2024,
  },
  {
    name: "Lula (Tupi) Field",
    type: "oil",
    subtype: "deepwater",
    lat: -25.2,
    lng: -42.0,
    estimatedReserves: 8.3,
    unit: "Bbbl",
    country: "Brazil",
    iso3: "BRA",
    year: 2024,
  },
  {
    name: "Johan Sverdrup",
    type: "oil",
    subtype: "offshore",
    lat: 58.9,
    lng: 2.5,
    estimatedReserves: 2.7,
    unit: "Bbbl",
    country: "Norway",
    iso3: "NOR",
    year: 2024,
  },
  {
    name: "Stabroek Block (Liza)",
    type: "oil",
    subtype: "deepwater",
    lat: 6.6,
    lng: -57.8,
    estimatedReserves: 11,
    unit: "Bbbl",
    country: "Guyana",
    iso3: "GUY",
    year: 2024,
  },
  {
    name: "Jubilee Field",
    type: "oil",
    subtype: "deepwater",
    lat: 4.8,
    lng: -3.15,
    estimatedReserves: 1.8,
    unit: "Bbbl",
    country: "Ghana",
    iso3: "GHA",
    year: 2024,
  },
  {
    name: "Agbami Field",
    type: "oil",
    subtype: "deepwater",
    lat: 4.2,
    lng: 4.4,
    estimatedReserves: 1.0,
    unit: "Bbbl",
    country: "Nigeria",
    iso3: "NGA",
    year: 2024,
  },

  // ──────────────── Shale / Tight Oil ────────────────
  {
    name: "Permian Basin",
    type: "shale",
    subtype: "tight_oil",
    lat: 31.9,
    lng: -102.1,
    estimatedReserves: 46.3,
    unit: "Bbbl",
    country: "United States",
    iso3: "USA",
    year: 2024,
  },
  {
    name: "Eagle Ford Shale",
    type: "shale",
    subtype: "tight_oil",
    lat: 28.8,
    lng: -98.5,
    estimatedReserves: 4.6,
    unit: "Bbbl",
    country: "United States",
    iso3: "USA",
    year: 2024,
  },
  {
    name: "Bakken Formation",
    type: "shale",
    subtype: "tight_oil",
    lat: 47.5,
    lng: -103.0,
    estimatedReserves: 7.4,
    unit: "Bbbl",
    country: "United States",
    iso3: "USA",
    year: 2024,
  },
  {
    name: "Vaca Muerta",
    type: "shale",
    subtype: "tight_oil",
    lat: -38.2,
    lng: -69.2,
    estimatedReserves: 16.2,
    unit: "Bbbl",
    country: "Argentina",
    iso3: "ARG",
    year: 2024,
  },
  {
    name: "DJ Basin (Niobrara)",
    type: "shale",
    subtype: "tight_oil",
    lat: 40.0,
    lng: -104.5,
    estimatedReserves: 2.0,
    unit: "Bbbl",
    country: "United States",
    iso3: "USA",
    year: 2024,
  },

  // ──────────────── Natural Gas ────────────────
  {
    name: "South Pars / North Dome",
    type: "natural_gas",
    subtype: "conventional",
    lat: 26.0,
    lng: 52.0,
    estimatedReserves: 1800,
    unit: "Tcf",
    country: "Iran / Qatar",
    iso3: "QAT",
    year: 2024,
  },
  {
    name: "Urengoy Field",
    type: "natural_gas",
    subtype: "conventional",
    lat: 66.0,
    lng: 76.0,
    estimatedReserves: 275,
    unit: "Tcf",
    country: "Russia",
    iso3: "RUS",
    year: 2024,
  },
  {
    name: "Yamburg Field",
    type: "natural_gas",
    subtype: "conventional",
    lat: 68.0,
    lng: 76.0,
    estimatedReserves: 148,
    unit: "Tcf",
    country: "Russia",
    iso3: "RUS",
    year: 2024,
  },
  {
    name: "Galkynysh Field",
    type: "natural_gas",
    subtype: "conventional",
    lat: 36.7,
    lng: 62.4,
    estimatedReserves: 500,
    unit: "Tcf",
    country: "Turkmenistan",
    iso3: "TKM",
    year: 2024,
  },
  {
    name: "Hassi R'Mel",
    type: "natural_gas",
    subtype: "conventional",
    lat: 33.0,
    lng: 3.3,
    estimatedReserves: 135,
    unit: "Tcf",
    country: "Algeria",
    iso3: "DZA",
    year: 2024,
  },
  {
    name: "Groningen Field",
    type: "natural_gas",
    subtype: "conventional",
    lat: 53.3,
    lng: 6.8,
    estimatedReserves: 60,
    unit: "Tcf",
    country: "Netherlands",
    iso3: "NLD",
    year: 2024,
  },
  {
    name: "Marcellus Shale",
    type: "natural_gas",
    subtype: "shale_gas",
    lat: 41.0,
    lng: -77.5,
    estimatedReserves: 410,
    unit: "Tcf",
    country: "United States",
    iso3: "USA",
    year: 2024,
  },
  {
    name: "Shtokman Field",
    type: "natural_gas",
    subtype: "offshore",
    lat: 73.1,
    lng: 44.0,
    estimatedReserves: 132,
    unit: "Tcf",
    country: "Russia",
    iso3: "RUS",
    year: 2024,
  },
  {
    name: "Haynesville Shale",
    type: "natural_gas",
    subtype: "shale_gas",
    lat: 32.5,
    lng: -93.5,
    estimatedReserves: 75,
    unit: "Tcf",
    country: "United States",
    iso3: "USA",
    year: 2024,
  },

  // ──────────────── Coal ────────────────
  {
    name: "Powder River Basin",
    type: "coal",
    subtype: "sub-bituminous",
    lat: 44.5,
    lng: -106.0,
    estimatedReserves: 200,
    unit: "Bt",
    country: "United States",
    iso3: "USA",
    year: 2024,
  },
  {
    name: "Illinois Basin",
    type: "coal",
    subtype: "bituminous",
    lat: 38.0,
    lng: -88.0,
    estimatedReserves: 150,
    unit: "Bt",
    country: "United States",
    iso3: "USA",
    year: 2024,
  },
  {
    name: "Bowen Basin",
    type: "coal",
    subtype: "bituminous",
    lat: -22.5,
    lng: 148.0,
    estimatedReserves: 27,
    unit: "Bt",
    country: "Australia",
    iso3: "AUS",
    year: 2024,
  },
  {
    name: "Kuzbass Basin",
    type: "coal",
    subtype: "bituminous",
    lat: 54.0,
    lng: 87.0,
    estimatedReserves: 110,
    unit: "Bt",
    country: "Russia",
    iso3: "RUS",
    year: 2024,
  },
  {
    name: "Shanxi Coal Basin",
    type: "coal",
    subtype: "bituminous",
    lat: 37.0,
    lng: 112.0,
    estimatedReserves: 120,
    unit: "Bt",
    country: "China",
    iso3: "CHN",
    year: 2024,
  },

  // ──────────────── Oil Sands ────────────────
  {
    name: "Athabasca Oil Sands",
    type: "oil_sands",
    subtype: "bitumen",
    lat: 57.0,
    lng: -111.5,
    estimatedReserves: 166,
    unit: "Bbbl",
    country: "Canada",
    iso3: "CAN",
    year: 2024,
  },
];
